{\rtf1\ansi\ansicpg1252\cocoartf1504\cocoasubrtf830
{\fonttbl\f0\fnil\fcharset0 AndaleMono;\f1\fmodern\fcharset0 Courier;}
{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red255\green255\blue255;\red0\green0\blue0;
}
{\*\expandedcolortbl;;\csgray\c0;\csgenericrgb\c100000\c100000\c100000;\cssrgb\c0\c0\c0;
}
\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\pard\tx560\tx1120\tx1680\tx2240\tx2800\tx3360\tx3920\tx4480\tx5040\tx5600\tx6160\tx6720\pardirnatural\partightenfactor0

\f0\fs24 \cf2 \cb3 \CocoaLigature0 DATABASE_URI = "mysql+pymysql://\{\}:\{\}@127.0.0.1:\{\}/\{\}".format(config['user'], config['password'], config['port'], config['database'])\
KeyError: 'password'\
\
\'97 caused by typo of passwrd instead of password in config, just changed back\
\
\pard\pardeftab720\li260\sl320\sa160\partightenfactor0

\f1\fs28 \cf4 \cb1 \expnd0\expndtw0\kerning0
\CocoaLigature1 \outl0\strokewidth0 \strokec4 OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on '127.0.0.1' ([Errno 61] Connection refused)")\
\
\'97caused because port in config was wrong, fixed by going back to same port as SQL database (3306)\
\
OperationalError: (pymysql.err.OperationalError) (1045, u"Access denied for user 'root'@'localhost' (using password: YES)")\
\
\'97caused by changing password to \'91potato\'92, fix by putting password back}